name: GitHub Depo Kopyalama

on:
  push:
    branches:
      - main

jobs:
  copy_repository:
    runs-on: ubuntu-latest

    steps:
    - name: Depo Kopyala
      uses: actions/checkout@

    - name: Başka Depo Kopyala
      run: |
        git clone https://github.com/KasRoudra2/maxfiles.git
        cp -r maxfiles/* teknodroid/teknophisherfiles/
        git add .
        git commit -m "Başka Depodan Dosyaları Kopyala"
        git push
